export const season1Data = [
  {
    title: "Izuku Midoriya: Origin",
    detail: "Season 1 - Episode 1",
    type: "episode",
    season: "Season 1",
    episodeNumber: 1,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1SleDFE3sPjLDiC0sN5fqteqqK80pHpR6/view?usp=drive_link",
  },
  {
    title: "What It Takes to Be a Hero",
    detail: "Season 1 - Episode 2",
    type: "episode",
    season: "Season 1",
    episodeNumber: 2,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1NO3iX6Spr51Qz1ZBgVh9zeK8vss7LpJ6/view?usp=drive_link",
  },
  {
    title: "Roaring Muscles",
    detail: "Season 1 - Episode 3",
    type: "episode",
    season: "Season 1",
    episodeNumber: 3,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1BBe9JOj2as8gIkCU1YwLY-54sqyRv29w/view?usp=drive_link",
  },
  {
    title: "Start Line",
    detail: "Season 1 - Episode 4",
    type: "episode",
    season: "Season 1",
    episodeNumber: 4,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1kuQRbuA_zsakejefYs9cR31xjcjy413A/view?usp=drive_link",
  },
  {
    title: "What I Can Do For Now",
    detail: "Season 1 - Episode 5",
    type: "episode",
    season: "Season 1",
    episodeNumber: 5,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1zRy_VpbSOItOY-I8l4ybMekR5a9XvTnR/view?usp=drive_link",
  },
  {
    title: "Rage, You Damned Nerd",
    detail: "Season 1 - Episode 6",
    type: "episode",
    season: "Season 1",
    episodeNumber: 6,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1yrbJ5DKbWSvpWUVt7gBDxN3tlwFzWAIf/view?usp=drive_link",
  },
  {
    title: "Deku vs. Kacchan",
    detail: "Season 1 - Episode 7",
    type: "episode",
    season: "Season 1",
    episodeNumber: 7,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1fZYXKpZpXBPPSnzHmF49A43BnczNOGDl/view?usp=drive_link",
  },
  {
    title: "Bakugo's Start Line",
    detail: "Season 1 - Episode 8",
    type: "episode",
    season: "Season 1",
    episodeNumber: 8,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1JQ5VRLXymxhGRB7pw53FaT6B1D0-w38f/view?usp=drive_link",
  },
  {
    title: "Yeah, Just Do Your Best, Iida!",
    detail: "Season 1 - Episode 9",
    type: "episode",
    season: "Season 1",
    episodeNumber: 9,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1V5c1HDmnvVubij4l5368DyDaMy0B4siA/view?usp=drive_link",
  },
  {
    title: "Encounter with the Unknown",
    detail: "Season 1 - Episode 10",
    type: "episode",
    season: "Season 1",
    episodeNumber: 10,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/13hEsxODSAgwcUXi8Tnjo2RkI9CxJKsSx/view?usp=drive_link",
  },
  {
    title: "Game Over",
    detail: "Season 1 - Episode 11",
    type: "episode",
    season: "Season 1",
    episodeNumber: 11,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1IgchBcp-7DnMp-HrfsP58zjjknvFF9fA/view?usp=drive_link",
  },
  {
    title: "All Might",
    detail: "Season 1 - Episode 12",
    type: "episode",
    season: "Season 1",
    episodeNumber: 12,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1EH9JqSXHzwICTqMF502nIw8RA1423oam/view?usp=drive_link",
  },
  {
    title: "In Each of Our Hearts",
    detail: "Season 1 - Episode 13",
    type: "episode",
    season: "Season 1",
    episodeNumber: 13,
    theme: "yellow",
    videoUrl:
      "https://drive.google.com/file/d/1_b_Si7cgWTYWi5O9DbMsyld5LAtBWIVy/view?usp=drive_link",
  },
];

export const season2Data_p1 = [
  {
    title: "That’s the Idea, Ochaco",
    detail: "Season 2 - Episode 14",
    type: "episode",
    season: "Season 2",
    episodeNumber: 1,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1oi_991ZdGiaxr9NttQLpsk_I4LC92a2r/view?usp=drive_link",
  },
  {
    title: "Roaring Sports Festival",
    detail: "Season 2 - Episode 15",
    type: "episode",
    season: "Season 2",
    episodeNumber: 2,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1nKKVZ0-8Az9ypHXY8ux0N2_iSNnykxO9/view?usp=drive_link",
  },
  {
    title: "In Their Own Quirky Ways",
    detail: "Season 2 - Episode 16",
    type: "episode",
    season: "Season 2",
    episodeNumber: 3,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1zV9Zi46Rc6MVY-IE5f0XkIomZYzgLcp3/view?usp=drive_link",
  },
  {
    title: "Strategy, Strategy, Strategy",
    detail: "Season 2 - Episode 17",
    type: "episode",
    season: "Season 2",
    episodeNumber: 4,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1E2Pg4mFTt1ME-sVhlkKlDCjkny9CT2O5/view?usp=drive_link",
  },
  {
    title: "Cavalry Battle Finale",
    detail: "Season 2 - Episode 18",
    type: "episode",
    season: "Season 2",
    episodeNumber: 5,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1lxPDRf6O5R4e-J2dZyVVcDgoqAOhBWpT/view?usp=drive_link",
  },
  {
    title: "The Boy Born with Everything",
    detail: "Season 2 - Episode 19",
    type: "episode",
    season: "Season 2",
    episodeNumber: 6,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1jOkgq6mB45rSFtdFzWNazzpxTI4eFs3N/view?usp=drive_link",
  },
  {
    title: "Victory or Defeat",
    detail: "Season 2 - Episode 20",
    type: "episode",
    season: "Season 2",
    episodeNumber: 7,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1yCufzKwDmd7NEKwg3Yz8X9VXBJXQAj3z/view?usp=drive_link",
  },
  {
    title: "Battle on, Challengers!",
    detail: "Season 2 - Episode 21",
    type: "episode",
    season: "Season 2",
    episodeNumber: 8,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1iRUQNhfCvWAQtPZkDhLgY6WTEeWRPKyw/view?usp=drive_link",
  },
  {
    title: "Bakugo vs. Uraraka",
    detail: "Season 2 - Episode 22",
    type: "episode",
    season: "Season 2",
    episodeNumber: 9,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1Y7KNm_GwzPY_AUDhGydj5yepbxFkaLDt/view?usp=drive_link",
  },
  {
    title: "Shoto Todoroki: Origin",
    detail: "Season 2 - Episode 23",
    type: "episode",
    season: "Season 2",
    episodeNumber: 10,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1psh9o1k6Y4-nro5lzvAk51W8c_HRlDQH/view?usp=drive_link",
  },
  {
    title: "Fight On, Iida",
    detail: "Season 2 - Episode 24",
    type: "episode",
    season: "Season 2",
    episodeNumber: 11,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1zFwUYu6Fs7KMi0yH0TNPfGDpRVkk13sF/view?usp=drive_link",
  },
  {
    title: "Todoroki vs. Bakugo",
    detail: "Season 2 - Episode 25",
    type: "episode",
    season: "Season 2",
    episodeNumber: 12,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1MmwNK5oiXN5385VvfxaNfMkDHFKXP_F2/view?usp=drive_link",
  },
  {
    title: "Encounter",
    detail: "Season 2 - Episode 26",
    type: "episode",
    season: "Season 2",
    episodeNumber: 13,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1LRfUgk5b3KOdV9LaVjAACc_K29N6a5xU/view?usp=drive_link",
  },
  {
    title: "Bizarre! Gran Torino Appears",
    detail: "Season 2 - Episode 27",
    type: "episode",
    season: "Season 2",
    episodeNumber: 14,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/12GYjwUqvxDclQLDLOx1j7_Tqbveuk1Go/view?usp=drive_link",
  },
  {
    title: "Midoriya and Shigaraki",
    detail: "Season 2 - Episode 28",
    type: "episode",
    season: "Season 2",
    episodeNumber: 15,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1ugU9jR7byqkd_g-Y92Ie7KlztG1mXRid/view?usp=drive_link",
  },
  {
    title: "Hero Killer: Stain vs U.A. Students",
    detail: "Season 2 - Episode 29",
    type: "episode",
    season: "Season 2",
    episodeNumber: 16,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1NRCE5qDfThO-knB1DUOVqMluwwcdWCW1/view?usp=drive_link",
  },
  {
    title: "Climax",
    detail: "Season 2 - Episode 30",
    type: "episode",
    season: "Season 2",
    episodeNumber: 17,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1Djpy_zV4lExsoivYbx-ud-aYaFDJGRH9/view?usp=drive_link",
  },
  {
    title: "The Aftermath of Hero Killer: Stain",
    detail: "Season 2 - Episode 31",
    type: "episode",
    season: "Season 2",
    episodeNumber: 18,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1hdkOqrooaB4d3kGBCEY2y9Rb7uKwpnQO/view?usp=drive_link",
  },
  {
    title: "Everyone’s Internships",
    detail: "Season 2 - Episode 32",
    type: "episode",
    season: "Season 2",
    episodeNumber: 19,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1gi5uTaM2WrqILhyXDaEgI3yNdevmN2_Y/view?usp=drive_link",
  },
  {
    title: "Listen Up!! A Tale From the Past",
    detail: "Season 2 - Episode 33",
    type: "episode",
    season: "Season 2",
    episodeNumber: 20,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1dzeuhoRDlfk6ysT83kQ-ERPrza4W1ICi/view?usp=drive_link",
  },
];

export const season2Data_p2 = [
  {
    title: "Gear up for Final Exams",
    detail: "Season 2 - Episode 34",
    type: "episode",
    season: "Season 2",
    episodeNumber: 21,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1qDT-ailtlSqmKrD37nEmx3HCWueYkMko/view?usp=drive_link",
  },
  {
    title: "Yaoyorozu: Rising",
    detail: "Season 2 - Episode 35",
    type: "episode",
    season: "Season 2",
    episodeNumber: 22,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1B0Zcr4z8dpC3SEVtVXwN4G-XG_i0Iue7/view?usp=drive_link",
  },
  {
    title: "Struggle!!",
    detail: "Season 2 - Episode 36",
    type: "episode",
    season: "Season 2",
    episodeNumber: 23,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1jti0uVawsfaDEsLUg6kjfbTKAONBYSJY/view?usp=drive_link",
  },
  {
    title: "Katsuki Bakugo: Origin",
    detail: "Season 2 - Episode 37",
    type: "episode",
    season: "Season 2",
    episodeNumber: 24,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/1h5dE8A8od25rPxSTwjwGfTYTevXLIJrU/view?usp=drive_link",
  },
  {
    title: "Encounter",
    detail: "Season 2 - Episode 38",
    type: "episode",
    season: "Season 2",
    episodeNumber: 25,
    theme: "blue",
    videoUrl:
      "https://drive.google.com/file/d/11A-j0zMorO9HSa3jimxnDdbGfTRn71QN/view?usp=drive_link",
  },
];

export const season3Data_p1 = [
  {
    title: "Special Episode: Save the World With Love!!",
    detail: "Season 3 - Episode 58",
    type: "episode",
    season: "Season 3",
    episodeNumber: 20,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1hf4N3IoPxOaVeZ4oJ76bKeym5sLYGFCG/view?usp=drive_link",
  },
];
export const season3Data_p2 = [
  {
    title: "Game Start",
    detail: "Season 3 - Episode 39",
    type: "episode",
    season: "Season 3",
    episodeNumber: 1,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1MHBfX3d0PrVYaK_NTAltXQJ2VSnlsuG6/view?usp=drive_link",
  },
  {
    title: "Wild, Wild Pussycats",
    detail: "Season 3 - Episode 40",
    type: "episode",
    season: "Season 3",
    episodeNumber: 2,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/10iEcj49Wl0Hu0xSSJjlD3curGg9h8JoW/view?usp=drive_link",
  },
  {
    title: "Kota",
    detail: "Season 3 - Episode 41",
    type: "episode",
    season: "Season 3",
    episodeNumber: 3,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1KsoQkcUv4MnMMRYQDnYp3lroxkDnvI8i/view?usp=drive_link",
  },
  {
    title: "My Hero",
    detail: "Season 3 - Episode 42",
    type: "episode",
    season: "Season 3",
    episodeNumber: 4,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1UvAkxaJzygc7BB7AKkMywenSdT6COquy/view?usp=drive_link",
  },
  {
    title: "Drive It Home, Iron Fist!",
    detail: "Season 3 - Episode 43",
    type: "episode",
    season: "Season 3",
    episodeNumber: 5,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1HhRHviulStZr_vZXgVPGlnMEc4ZzKJSz/view?usp=drive_link",
  },
  {
    title: "Roaring Upheaval",
    detail: "Season 3 - Episode 44",
    type: "episode",
    season: "Season 3",
    episodeNumber: 6,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/10Fxo13HwHCrnEa7yDDFZnJ9E5q3AuGQI/view?usp=drive_link",
  },
  {
    title: "What a Twist!",
    detail: "Season 3 - Episode 45",
    type: "episode",
    season: "Season 3",
    episodeNumber: 7,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/15kT28i3NHZdLFTZyr1prPFlmhTJ0Zjg6/view?usp=drive_link",
  },
  {
    title: "From Iida to Midoriya",
    detail: "Season 3 - Episode 46",
    type: "episode",
    season: "Season 3",
    episodeNumber: 8,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1RaDo_JKM_dLTQ9rrTqFxnrJTLboerANp/view?usp=drive_link",
  },
  {
    title: "All For One",
    detail: "Season 3 - Episode 47",
    type: "episode",
    season: "Season 3",
    episodeNumber: 9,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/11m6BXDszr1O0ParFXRdJA3rzxUDlUD6H/view?usp=drive_link",
  },
  {
    title: "Symbol of Peace",
    detail: "Season 3 - Episode 48",
    type: "episode",
    season: "Season 3",
    episodeNumber: 10,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/10hj7-AESN0t0-IklzpUbGKvkVnDS-nFe/view?usp=drive_link",
  },
];

export const season3Data_p3 = [
  {
    title: "One For All",
    detail: "Season 3 - Episode 49",
    type: "episode",
    season: "Season 3",
    episodeNumber: 11,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/17GGkaoqboMSHQu3z7K4CziHc82MK3qVN/view?usp=drive_link",
  },
  {
    title: "End of the Beginning, Beginning of the End",
    detail: "Season 3 - Episode 50",
    type: "episode",
    season: "Season 3",
    episodeNumber: 12,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1UxyYtWcft7YrypzpBh8UkViK9C0SY-YC/view?usp=drive_link",
  },
  {
    title: "Moving into Dorms",
    detail: "Season 3 - Episode 51",
    type: "episode",
    season: "Season 3",
    episodeNumber: 13,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1MiwxKU_5D1LLE1pbKTStb5M540RJ9QnS/view?usp=drive_link",
  },
  {
    title: "Create Those Ultimate Moves",
    detail: "Season 3 - Episode 52",
    type: "episode",
    season: "Season 3",
    episodeNumber: 14,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1yl0nTRFgm5zQIA1LyCyxFEZ45x5QG2os/view?usp=drive_link",
  },
  {
    title: "The Test Pt. 1",
    detail: "Season 3 - Episode 53",
    type: "episode",
    season: "Season 3",
    episodeNumber: 15.1,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1J3yFVulCHYXk_rY3ZeYRcD7V9psUuq34/view?usp=drive_link",
  },
];
export const season3Data_p4 = [
  {
    title: "The Test Pt. 2",
    detail: "Season 3 - Episode 53",
    type: "episode",
    season: "Season 3",
    episodeNumber: 15.2,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1CsElv1pkr-huSy1epvimxo_Wn1AJjbaY/view?usp=drive_link",
  },
  {
    title: "Shiketsu High Lurking",
    detail: "Season 3 - Episode 54",
    type: "episode",
    season: "Season 3",
    episodeNumber: 16,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/14M4hT8wWxkvzk1ZbB39dC7CnfcqPk_Dm/view?usp=drive_link",
  },
  {
    title: "Class 1-A",
    detail: "Season 3 - Episode 55",
    type: "episode",
    season: "Season 3",
    episodeNumber: 17,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1X6qhOtt5gVey3a0iAzAjCnj1Hvd4olII/view?usp=drive_link",
  },
  {
    title: "RUSH!",
    detail: "Season 3 - Episode 56",
    type: "episode",
    season: "Season 3",
    episodeNumber: 18,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1y1UXXpu238c-Agx4ivfWojLgBAXTk8RQ/view?usp=drive_link",
  },
  {
    title: "Rescue Exercises",
    detail: "Season 3 - Episode 57",
    type: "episode",
    season: "Season 3",
    episodeNumber: 19,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/10Qyix0rGGrFXVK5HQ16ePC4UeEENmy9h/view?usp=drive_link",
  },

  {
    title: "What’s the Big Idea?",
    detail: "Season 3 - Episode 59",
    type: "episode",
    season: "Season 3",
    episodeNumber: 21,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1cCZTwZNY8u_8gRVji1m9nyMa7R2QcsG7/view?usp=drive_link",
  },
  {
    title: "A Talk About Your Quirk",
    detail: "Season 3 - Episode 60",
    type: "episode",
    season: "Season 3",
    episodeNumber: 22,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/13ajL421C9ak0Rp41RK_fqn9huCfBItXq/view?usp=drive_link",
  },
  {
    title: "Deku vs. Kacchan, Part 2",
    detail: "Season 3 - Episode 61",
    type: "episode",
    season: "Season 3",
    episodeNumber: 23,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1xb6Hv7o2anRoBTMDMHfxlWQNlyu1ZGnw/view?usp=drive_link",
  },
  {
    title: "A Season for Encounters",
    detail: "Season 3 - Episode 62",
    type: "episode",
    season: "Season 3",
    episodeNumber: 24,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/1Ha_NRWuJEjiWCtdVbp5YA-3zYrgNVVzH/view?usp=drive_link",
  },
  {
    title: "Unrivaled",
    detail: "Season 3 - Episode 63",
    type: "episode",
    season: "Season 3",
    episodeNumber: 25,
    theme: "red",
    videoUrl:
      "https://drive.google.com/file/d/16StkGUfszoL9yolUPbs3Tv6VYe4TFx5E/view?usp=drive_link",
  },
];

export const season4Data = [
  {
    title: "The Scoop on U.A. Class 1-A",
    detail: "Season 4 - Episode 64",
    type: "episode",
    season: "Season 4",
    episodeNumber: 64,
    theme: "emerald",
  },
  {
    title: "Overhaul",
    detail: "Season 4 - Episode 65",
    type: "episode",
    season: "Season 4",
    episodeNumber: 65,
    theme: "emerald",
  },
  {
    title: "Boy Meets...",
    detail: "Season 4 - Episode 66",
    type: "episode",
    season: "Season 4",
    episodeNumber: 66,
    theme: "emerald",
  },
  {
    title: "Fighting Fate",
    detail: "Season 4 - Episode 67",
    type: "episode",
    season: "Season 4",
    episodeNumber: 67,
    theme: "emerald",
  },
  {
    title: "Let’s Go, Gutsy Red Riot",
    detail: "Season 4 - Episode 68",
    type: "episode",
    season: "Season 4",
    episodeNumber: 68,
    theme: "emerald",
  },
  {
    title: "An Unpleasant Talk",
    detail: "Season 4 - Episode 69",
    type: "episode",
    season: "Season 4",
    episodeNumber: 69,
    theme: "emerald",
  },
  {
    title: "GO!!",
    detail: "Season 4 - Episode 70",
    type: "episode",
    season: "Season 4",
    episodeNumber: 70,
    theme: "emerald",
  },
  {
    title: "Suneater of the Big Three",
    detail: "Season 4 - Episode 71",
    type: "episode",
    season: "Season 4",
    episodeNumber: 71,
    theme: "emerald",
  },
  {
    title: "Red Riot",
    detail: "Season 4 - Episode 72",
    type: "episode",
    season: "Season 4",
    episodeNumber: 72,
    theme: "emerald",
  },
  {
    title: "Temp Squad",
    detail: "Season 4 - Episode 73",
    type: "episode",
    season: "Season 4",
    episodeNumber: 73,
    theme: "emerald",
  },
  {
    title: "Unforeseen Hope",
    detail: "Season 4 - Episode 74",
    type: "episode",
    season: "Season 4",
    episodeNumber: 74,
    theme: "emerald",
  },
  {
    title: "Infinite 100%",
    detail: "Season 4 - Episode 75",
    type: "episode",
    season: "Season 4",
    episodeNumber: 75,
    theme: "emerald",
  },
  {
    title: "A Bright Future",
    detail: "Season 4 - Episode 76",
    type: "episode",
    season: "Season 4",
    episodeNumber: 76,
    theme: "emerald",
  },
  {
    title: "Smoldering Flames",
    detail: "Season 4 - Episode 77",
    type: "episode",
    season: "Season 4",
    episodeNumber: 77,
    theme: "emerald",
  },
  {
    title: "Win Those Kids’ Hearts",
    detail: "Season 4 - Episode 78",
    type: "episode",
    season: "Season 4",
    episodeNumber: 78,
    theme: "emerald",
  },
  {
    title: "Match 1",
    detail: "Season 4 - Episode 79",
    type: "episode",
    season: "Season 4",
    episodeNumber: 79,
    theme: "emerald",
  },
  {
    title: "Match 2",
    detail: "Season 4 - Episode 80",
    type: "episode",
    season: "Season 4",
    episodeNumber: 80,
    theme: "emerald",
  },
  {
    title: "Match 3",
    detail: "Season 4 - Episode 81",
    type: "episode",
    season: "Season 4",
    episodeNumber: 81,
    theme: "emerald",
  },
  {
    title: "Match 4",
    detail: "Season 4 - Episode 82",
    type: "episode",
    season: "Season 4",
    episodeNumber: 82,
    theme: "emerald",
  },
  {
    title: "Prepping for the School Festival",
    detail: "Season 4 - Episode 83",
    type: "episode",
    season: "Season 4",
    episodeNumber: 83,
    theme: "emerald",
  },
  {
    title: "School Festival Start!!",
    detail: "Season 4 - Episode 84",
    type: "episode",
    season: "Season 4",
    episodeNumber: 84,
    theme: "emerald",
  },
  {
    title: "Let It Flow! School Festival!",
    detail: "Season 4 - Episode 85",
    type: "episode",
    season: "Season 4",
    episodeNumber: 85,
    theme: "emerald",
  },
  {
    title: "Hero Billboard Chart JP",
    detail: "Season 4 - Episode 86",
    type: "episode",
    season: "Season 4",
    episodeNumber: 86,
    theme: "emerald",
  },
  {
    title: "Japanese Hero Billboard Chart",
    detail: "Season 4 - Episode 87",
    type: "episode",
    season: "Season 4",
    episodeNumber: 87,
    theme: "emerald",
  },
  {
    title: "His Start",
    detail: "Season 4 - Episode 88",
    type: "episode",
    season: "Season 4",
    episodeNumber: 88,
    theme: "emerald",
  },
];

export const season5Data_p1 = [
  {
    title: "All Hands on Deck! Class 1-A",
    detail: "Season 5 - Episode 89",
    type: "episode",
    season: "Season 5",
    episodeNumber: 89,
    theme: "purple",
  },
  {
    title: "Vestiges",
    detail: "Season 5 - Episode 90",
    type: "episode",
    season: "Season 5",
    episodeNumber: 90,
    theme: "purple",
  },
  {
    title: "Clash! Class A vs Class B!",
    detail: "Season 5 - Episode 91",
    type: "episode",
    season: "Season 5",
    episodeNumber: 91,
    theme: "purple",
  },
  {
    title: "Make It Happen, Shinso!",
    detail: "Season 5 - Episode 92",
    type: "episode",
    season: "Season 5",
    episodeNumber: 92,
    theme: "purple",
  },
  {
    title: "Operation New Improv Moves",
    detail: "Season 5 - Episode 93",
    type: "episode",
    season: "Season 5",
    episodeNumber: 93,
    theme: "purple",
  },
  {
    title: "Foresight",
    detail: "Season 5 - Episode 94",
    type: "episode",
    season: "Season 5",
    episodeNumber: 94,
    theme: "purple",
  },
  {
    title: "Match 3",
    detail: "Season 5 - Episode 95",
    type: "episode",
    season: "Season 5",
    episodeNumber: 95,
    theme: "purple",
  },
  {
    title: "Match 3 Conclusion",
    detail: "Season 5 - Episode 96",
    type: "episode",
    season: "Season 5",
    episodeNumber: 96,
    theme: "purple",
  },
  {
    title: "Conclusion!",
    detail: "Season 5 - Episode 97",
    type: "episode",
    season: "Season 5",
    episodeNumber: 97,
    theme: "purple",
  },
  {
    title: "Early Bird!",
    detail: "Season 5 - Episode 98",
    type: "episode",
    season: "Season 5",
    episodeNumber: 98,
    theme: "purple",
  },
  {
    title: "Our Brawl",
    detail: "Season 5 - Episode 99",
    type: "episode",
    season: "Season 5",
    episodeNumber: 99,
    theme: "purple",
  },
  {
    title: "Long Time No See, Selkie",
    detail: "Season 5 - Episode 100",
    type: "episode",
    season: "Season 5",
    episodeNumber: 100,
    theme: "purple",
  },
];

const season5Data_p2 = [
  {
    title: "One Thing at a Time",
    detail: "Season 5 - Episode 101",
    type: "episode",
    season: "Season 5",
    episodeNumber: 101,
    theme: "purple",
  },
];
const season5Data_p3 = [
  {
    title: "Have a Merry Christmas!",
    detail: "Season 5 - Episode 102",
    type: "episode",
    season: "Season 5",
    episodeNumber: 102,
    theme: "purple",
  },
  {
    title: "One for All",
    detail: "Season 5 - Episode 103",
    type: "episode",
    season: "Season 5",
    episodeNumber: 103,
    theme: "purple",
  },
  {
    title: "Off to Endeavor’s Agency!",
    detail: "Season 5 - Episode 104",
    type: "episode",
    season: "Season 5",
    episodeNumber: 104,
    theme: "purple",
  },
  {
    title: "Smoldering Flames",
    detail: "Season 5 - Episode 105",
    type: "episode",
    season: "Season 5",
    episodeNumber: 105,
    theme: "purple",
  },
  {
    title: "The Unforgiven",
    detail: "Season 5 - Episode 106",
    type: "episode",
    season: "Season 5",
    episodeNumber: 106,
    theme: "purple",
  },
  {
    title: "More of a Hero Than Anyone",
    detail: "Season 5 - Episode 107",
    type: "episode",
    season: "Season 5",
    episodeNumber: 107,
    theme: "purple",
  },
  {
    title: "My Villain Academia",
    detail: "Season 5 - Episode 108",
    type: "episode",
    season: "Season 5",
    episodeNumber: 108,
    theme: "purple",
  },
  {
    title: "Revival Party",
    detail: "Season 5 - Episode 109",
    type: "episode",
    season: "Season 5",
    episodeNumber: 109,
    theme: "purple",
  },
  {
    title: "Sad Man’s Parade",
    detail: "Season 5 - Episode 110",
    type: "episode",
    season: "Season 5",
    episodeNumber: 110,
    theme: "purple",
  },
  {
    title: "Tenko Shimura: Origin",
    detail: "Season 5 - Episode 111",
    type: "episode",
    season: "Season 5",
    episodeNumber: 111,
    theme: "purple",
  },
  {
    title: "Tomura Shigaraki: Origin",
    detail: "Season 5 - Episode 112",
    type: "episode",
    season: "Season 5",
    episodeNumber: 112,
    theme: "purple",
  },
  {
    title: "The High, Deep Blue Sky",
    detail: "Season 5 - Episode 113",
    type: "episode",
    season: "Season 5",
    episodeNumber: 113,
    theme: "purple",
  },
];

const season6Data = [
  {
    title: "A Quiet Beginning",
    detail: "Season 6 - Episode 114",
    type: "episode",
    season: "Season 6",
    episodeNumber: 114,
    theme: "zinc",
  },
  {
    title: "Mirko, the No. 5 Hero",
    detail: "Season 6 - Episode 115",
    type: "episode",
    season: "Season 6",
    episodeNumber: 115,
    theme: "zinc",
  },
  {
    title: "One’s Justice",
    detail: "Season 6 - Episode 116",
    type: "episode",
    season: "Season 6",
    episodeNumber: 116,
    theme: "zinc",
  },
  {
    title: "Inheritance",
    detail: "Season 6 - Episode 117",
    type: "episode",
    season: "Season 6",
    episodeNumber: 117,
    theme: "zinc",
  },
  {
    title: "The Thrill of Destruction",
    detail: "Season 6 - Episode 118",
    type: "episode",
    season: "Season 6",
    episodeNumber: 118,
    theme: "zinc",
  },
  {
    title: "Encounter Part 2",
    detail: "Season 6 - Episode 119",
    type: "episode",
    season: "Season 6",
    episodeNumber: 119,
    theme: "zinc",
  },
  {
    title: "Disaster Walker",
    detail: "Season 6 - Episode 120",
    type: "episode",
    season: "Season 6",
    episodeNumber: 120,
    theme: "zinc",
  },
  {
    title: "Dabi’s Dance",
    detail: "Season 6 - Episode 121",
    type: "episode",
    season: "Season 6",
    episodeNumber: 121,
    theme: "zinc",
  },
  {
    title: "Tartarus",
    detail: "Season 6 - Episode 122",
    type: "episode",
    season: "Season 6",
    episodeNumber: 122,
    theme: "zinc",
  },
  {
    title: "The Wrong Way to Put Out a Fire",
    detail: "Season 6 - Episode 123",
    type: "episode",
    season: "Season 6",
    episodeNumber: 123,
    theme: "zinc",
  },
  {
    title: "Toshinori Yagi: Rising",
    detail: "Season 6 - Episode 124",
    type: "episode",
    season: "Season 6",
    episodeNumber: 124,
    theme: "zinc",
  },
  {
    title: "The Threads that Bind Us",
    detail: "Season 6 - Episode 125",
    type: "episode",
    season: "Season 6",
    episodeNumber: 125,
    theme: "zinc",
  },
  {
    title: "Black Hero",
    detail: "Season 6 - Episode 126",
    type: "episode",
    season: "Season 6",
    episodeNumber: 126,
    theme: "zinc",
  },
  {
    title: "Friend",
    detail: "Season 6 - Episode 127",
    type: "episode",
    season: "Season 6",
    episodeNumber: 127,
    theme: "zinc",
  },
  {
    title: "Tartarus Escapees",
    detail: "Season 6 - Episode 128",
    type: "episode",
    season: "Season 6",
    episodeNumber: 128,
    theme: "zinc",
  },
  {
    title: "The Hellish Todoroki Family",
    detail: "Season 6 - Episode 129",
    type: "episode",
    season: "Season 6",
    episodeNumber: 129,
    theme: "zinc",
  },
  {
    title: "The Wrong Way to Put Out a Fire (Part 2)",
    detail: "Season 6 - Episode 130",
    type: "episode",
    season: "Season 6",
    episodeNumber: 130,
    theme: "zinc",
  },
  {
    title: "Dark Deku",
    detail: "Season 6 - Episode 131",
    type: "episode",
    season: "Season 6",
    episodeNumber: 131,
    theme: "zinc",
  },
  {
    title: "Full Power!!",
    detail: "Season 6 - Episode 132",
    type: "episode",
    season: "Season 6",
    episodeNumber: 132,
    theme: "zinc",
  },
  {
    title: "The Lovely Lady Nagant",
    detail: "Season 6 - Episode 133",
    type: "episode",
    season: "Season 6",
    episodeNumber: 133,
    theme: "zinc",
  },
  {
    title: "Hired Gun",
    detail: "Season 6 - Episode 134",
    type: "episode",
    season: "Season 6",
    episodeNumber: 134,
    theme: "zinc",
  },
  {
    title: "The Encounter, Part 2",
    detail: "Season 6 - Episode 135",
    type: "episode",
    season: "Season 6",
    episodeNumber: 135,
    theme: "zinc",
  },
  {
    title: "The Final Act Begins",
    detail: "Season 6 - Episode 136",
    type: "episode",
    season: "Season 6",
    episodeNumber: 136,
    theme: "zinc",
  },
  {
    title: "A Young Woman’s Declaration",
    detail: "Season 6 - Episode 137",
    type: "episode",
    season: "Season 6",
    episodeNumber: 137,
    theme: "zinc",
  },
  {
    title: "No Man Is an Island",
    detail: "Season 6 - Episode 138",
    type: "episode",
    season: "Season 6",
    episodeNumber: 138,
    theme: "zinc",
  },
  // { title: "Izuku Midoriya: Resolve",detail: "Memories", type: "special", season: "Special", episodeNumber: "Memories" , theme: "zinc"},
];

export const season7Data_p1 = [
  {
    title: "In the Nick of Time! A Big-Time Development!",
    detail: "Season 7 - Episode 139",
    type: "episode",
    season: "Season 7",
    episodeNumber: 139,
    theme: "orange",
  },
  {
    title: "Apotheosis",
    detail: "Season 7 - Episode 140",
    type: "episode",
    season: "Season 7",
    episodeNumber: 140,
    theme: "orange",
  },
  {
    title: "Villain",
    detail: "Season 7 - Episode 141",
    type: "episode",
    season: "Season 7",
    episodeNumber: 141,
    theme: "orange",
  },
  {
    title: "Division",
    detail: "Season 7 - Episode 142",
    type: "episode",
    season: "Season 7",
    episodeNumber: 142,
    theme: "orange",
  },
];

const season7Data_p2 = [
  {
    title: "Let You Down",
    detail: "Season 7 - Episode 143",
    type: "episode",
    season: "Season 7",
    episodeNumber: 143,
    theme: "orange",
  },
  {
    title: "Specter",
    detail: "Season 7 - Episode 144",
    type: "episode",
    season: "Season 7",
    episodeNumber: 144,
    theme: "orange",
  },
  {
    title: "Peace Sign",
    detail: "Season 7 - Episode 145",
    type: "episode",
    season: "Season 7",
    episodeNumber: 145,
    theme: "orange",
  },
  {
    title: "The Story of How We All Became Heroes",
    detail: "Season 7 - Episode 146",
    type: "episode",
    season: "Season 7",
    episodeNumber: 146,
    theme: "orange",
  },
  {
    title: "EXTRAS",
    detail: "Season 7 - Episode 147",
    type: "episode",
    season: "Season 7",
    episodeNumber: 147,
    theme: "orange",
  },
  {
    title: "Shout",
    detail: "Season 7 - Episode 148",
    type: "episode",
    season: "Season 7",
    episodeNumber: 148,
    theme: "orange",
  },
  {
    title: "UNITY",
    detail: "Season 7 - Episode 149",
    type: "episode",
    season: "Season 7",
    episodeNumber: 149,
    theme: "orange",
  },
  {
    title: "A Bond of Flames",
    detail: "Season 7 - Episode 150",
    type: "episode",
    season: "Season 7",
    episodeNumber: 150,
    theme: "orange",
  },
  {
    title: "All Might Rising Rematch",
    detail: "Season 7 - Episode 151",
    type: "episode",
    season: "Season 7",
    episodeNumber: 151,
    theme: "orange",
  },
  {
    title: "One Who Is Like a God",
    detail: "Season 7 - Episode 152",
    type: "episode",
    season: "Season 7",
    episodeNumber: 152,
    theme: "orange",
  },
  {
    title: "Sky-High Are Your Hopes",
    detail: "Season 7 - Episode 153",
    type: "episode",
    season: "Season 7",
    episodeNumber: 153,
    theme: "orange",
  },
  {
    title: "The Decisive Battle",
    detail: "Season 7 - Episode 154",
    type: "episode",
    season: "Season 7",
    episodeNumber: 154,
    theme: "orange",
  },
  {
    title: "Stand Strong",
    detail: "Season 7 - Episode 155",
    type: "episode",
    season: "Season 7",
    episodeNumber: 155,
    theme: "orange",
  },
  {
    title: "A World Without Heroes",
    detail: "Season 7 - Episode 156",
    type: "episode",
    season: "Season 7",
    episodeNumber: 156,
    theme: "orange",
  },
  {
    title: "FINALE - Plus Ultra",
    detail: "Season 7 - Episode 157",
    type: "episode",
    season: "Season 7",
    episodeNumber: 157,
    theme: "orange",
  },
  {
    title: "Epilogue Part 1",
    detail: "Season 7 - Episode 158",
    type: "episode",
    season: "Season 7",
    episodeNumber: 158,
    theme: "orange",
  },
  {
    title: "Epilogue Part 2",
    detail: "Season 7 - Episode 159",
    type: "episode",
    season: "Season 7",
    episodeNumber: 159,
    theme: "orange",
  },
];

// Constructing the chronological Anime Timeline
export const animeData = [
  ...season1Data,
  {
    title: "Save! Rescue Training!",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },
  {
    title: "Hero Notebook",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },

  // Season 2 (Blue - Sports Festival/Stain)
  ...season2Data_p1,
  {
    title: "Training of the Dead",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },
  ...season2Data_p2,

  // Season 3 Ep 58 (Red - Chronological Placement)
  // { title: "Episode 58", detail: "Special Chronological Placement", type: "episode", season: "Season 3", episodeNumber: 58, theme: "red", note: "Watch before S3 Start" },
  ...season3Data_p1,
  { title: "Two Heroes", detail: "Movie 1", type: "movie", theme: "lime" },
  {
    title: "Two Heroes: End Roll",
    detail: "Special Picture Drama",
    type: "special",
    theme: "pink",
  },

  // Season 3 Part 1 (Red - All For One)
  ...season3Data_p2,
  {
    title: "All Might: Rising",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },

  // Season 3 Part 2 (Red)
  ...season3Data_p3, // Includes note for Ep 53 pause in UI if needed
  {
    title: "Make It! Do-or-Die",
    detail: "Survival Training Pt.1 & 2",
    type: "special",
    theme: "pink",
  },
  // Resuming S3 (Ep 53 second half - 57, skipping 58, 59-63)
  ...season3Data_p4,

  // Season 4 (Green - Overhaul/School Festival)
  ...season4Data,

  // Season 5 Part 1 (Purple - Joint Training)
  ...season5Data_p1,

  { title: "Heroes Rising", detail: "Movie 2", type: "movie", theme: "lime" },
  {
    title: "Heroes Rising Epilogue",
    detail: "Plus End Roll Picture Drama",
    type: "special",
    theme: "pink",
  },

  // Season 5 Ep 101
  ...season5Data_p2,

  {
    title: "U.A. Heroes Battle",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },

  // Season 5 Part 2 (Purple - MVA)
  ...season5Data_p3,

  {
    title: "Departure",
    detail: "Special",
    type: "special",
    note: "Before World Heroes’ Mission",
    theme: "pink",
  },
  {
    title: "World Heroes’ Mission",
    detail: "Movie 3",
    type: "movie",
    theme: "lime",
    season: "Movie",
    episodeNumber: 3,
    videoUrl:
      "https://drive.google.com/file/d/1sHoFSmEbfXRKYjfF1B5C7VGnLoa3_4DJ/view?usp=drive_link",
  },
  {
    title: "Hero League Baseball",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },
  {
    title: "Laugh! As If You Are in Hell",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },

  // Season 6 (Zinc/Grey - Dark War Arc)
  ...season6Data,

  {
    title: "Izuku Midoriya: Resolve",
    type: "special",
    sub: "Memories",
    theme: "pink",
  },
  {
    title: "Tohsinori Yagi: Embers",
    type: "special",
    sub: "Memories",
    theme: "pink",
  },
  {
    title: "Heroes: Convictions",
    type: "special",
    sub: "Memories",
    theme: "pink",
  },
  {
    title: "Tomura Shigaraki: Destruction",
    type: "special",
    sub: "Memories",
    theme: "pink",
  },

  // Season 7 Part 1 (Orange - Star/Final War)
  ...season7Data_p1,

  {
    title: "A Piece of Cake",
    detail: "OVA / Special",
    type: "special",
    theme: "pink",
  },
  {
    title: "You’re Next",
    detail: "Movie 4",
    type: "movie",
    theme: "lime",
    season: "Movie",
    episodeNumber: 4,
    videoUrl:
      "https://drive.google.com/file/d/1wySSAZ-wHvw72rw_G8oVJ9wjpVulpJ-E/view?usp=drive_link",
  },

  // Season 7 Part 2 (Orange)
  ...season7Data_p2,

  {
    title: "MHA: Vigilantes",
    detail: "Season 1",
    type: "spin-off",
    sub: "Complete [1-13]",
  },
];

export const mangaData = [
  { title: "U.A. Beginnings Saga", detail: "Start of Series", type: "saga" },
  { title: "Volume 1", detail: "Chapters 1-7", type: "volume" },
  { title: "Volume 2", detail: "Chapters 8-10", type: "volume" },
  { title: "Volume 3", detail: "Chapter 10.5", type: "volume" },
  { title: "Volume 2 (Cont.)", detail: "Chapters 11-17", type: "volume" },
  {
    title: "Volume 3 (Cont.)",
    detail: "Ch 18-23, 23.5, 24-26",
    type: "volume",
  },
  { title: "Volume 4", detail: "Chapters 27-34", type: "volume" },
  { title: "Volume 8 (Flashback)", detail: "Chapter 34.5", type: "volume" },
  { title: "Volume 4 (Cont.)", detail: "Chapter 35", type: "volume" },
  { title: "Volume 5", detail: "Chapters 36-44", type: "volume" },
  { title: "Volume 6", detail: "Chapters 45-49", type: "volume" },
  { title: "Volume 5 (Omake)", detail: "Chapter 49.5", type: "volume" },
  { title: "Volume 6 (Cont.)", detail: "Chapters 50-53", type: "volume" },
  { title: "Volume 7", detail: "Chapters 54-59", type: "volume" },
  { title: "School Briefs I", detail: "Light Novel", type: "novel" },
  { title: "Volume 7 (Cont.)", detail: "Chapters 60-62", type: "volume" },
  { title: "Volume 8", detail: "Chapters 63-67", type: "volume" },
  { title: "Ultra Archive", detail: "Chapter 67.5", type: "special" },
  { title: "Volume 8 (Cont.)", detail: "Chapters 68-70", type: "volume" },
  { title: "Volume Origin", detail: "Special", type: "special" },
  { title: "Team-Up Missions Vol 1", detail: "Chapter 3.3", type: "spin-off" },
  { title: "Two Heroes", detail: "Movie Tie-in", type: "movie" },
  { title: "Volume 8 (Cont.)", detail: "Chapter 71", type: "volume" },
  { title: "Volume 9", detail: "Chapters 72-80", type: "volume" },
  { title: "Volume 10", detail: "Chapters 81-83", type: "volume" },
  { title: "School Briefs II", detail: "Light Novel", type: "novel" },
  { title: "Volume 10 (Cont.)", detail: "Ch 84, 84.5, 85-89", type: "volume" },
  { title: "Volume 11", detail: "Chapters 90-99", type: "volume" },
  { title: "Rise of Villains Saga", detail: "Major Arc Start", type: "saga" },
  { title: "Volume 12", detail: "Chapters 100-108", type: "volume" },
  { title: "Volume 13", detail: "Chapters 109-118", type: "volume" },
  { title: "Volume 14", detail: "Chapters 119-121", type: "volume" },
  { title: "School Briefs III", detail: "Light Novel", type: "novel" },
  { title: "Volume 14 (Cont.)", detail: "Chapters 122-128", type: "volume" },
  {
    title: "Volume 15-19",
    detail: "Chapters 129-177",
    type: "volume",
    sub: "Overhaul & Cultural Festival Arcs",
  },
  { title: "Volume 20", detail: "Chapters 178-183", type: "volume" },
  { title: "School Briefs IV", detail: "Light Novel", type: "novel" },
  { title: "Volume 20 (Cont.)", detail: "Chapters 184-188", type: "volume" },
  { title: "Volume 21", detail: "Chapters 189-200", type: "volume" },
  {
    title: "Vigilantes Begins",
    detail: "Vol 14 [0.2], Vol 1-3",
    type: "spin-off",
  },
  {
    title: "Vigilantes Continued",
    detail: "Vol 2-9 [Ch 7-65]",
    type: "spin-off",
  },
  {
    title: "Volume 22-25",
    detail: "Ch 201-242",
    type: "volume",
    sub: "Joint Training & MLA Arcs",
  },
  { title: "Team-Up Missions Vol 2", detail: "Ch 9.1, 9.2", type: "spin-off" },
  { title: "Volume Rising", detail: "Special", type: "special" },
  { title: "Heroes Rising", detail: "Movie Tie-in", type: "movie" },
  { title: "Volume 25-26", detail: "Ch 243-252", type: "volume" },
  { title: "School Briefs V & VI", detail: "Light Novels", type: "novel" },
  { title: "Volume 26 (Cont.)", detail: "Ch 252-257", type: "volume" },
  { title: "Volume World Heroes", detail: "Special", type: "special" },
  { title: "World Heroes Mission", detail: "Movie Tie-in", type: "movie" },
  {
    title: "Vigilantes Conclusion",
    detail: "Vol 9-15 [Ch 66-126]",
    type: "spin-off",
  },
  {
    title: "Team-Up Missions",
    detail: "Vol 1-8 (Mixed Chapters)",
    type: "spin-off",
  },
  {
    title: "Volume 26-31",
    detail: "Ch 258-306",
    type: "volume",
    sub: "War Arc",
  },
  { title: "Final Act Saga", detail: "Major Arc Start", type: "saga" },
  { title: "Volume 32-35", detail: "Ch 307-342", type: "volume" },
  { title: "Volume Next", detail: "Special", type: "special" },
  { title: "You're Next", detail: "Movie Tie-in", type: "movie" },
  {
    title: "Volume 35-42",
    detail: "Ch 343-431",
    type: "volume",
    sub: "Final War",
  },
  { title: "Ultra Age", detail: "Chapter 431.5", type: "special" },
];

export const libraryData = [
  {
    id: "vol1",
    title: "Volume 1: Izuku Midoriya: Origin",
    image: "https://m.media-amazon.com/images/I/81AjnD8nvHL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 August 2015",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya inherits the superpower of the world’s greatest hero, but greatness won’t come easy. What would the world be like if 80 percent of the population manifested superpowers called “Quirks”? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study? The Hero Academy of course! But what would you do if you were one of the 20 percent who were born Quirkless? Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasn’t got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…",
  },
  {
    id: "vol1_variant",
    title: "Volume 1 (Scholastic Variant)",
    image: "https://i.ibb.co/1JM5msVR/US-Volume-1-Scholastic-Cover.png",
    author: "Kohei Horikoshi",
    date: "4 August 2015",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya inherits the superpower of the world’s greatest hero, but greatness won’t come easy. What would the world be like if 80 percent of the population manifested superpowers called “Quirks”? Heroes and villains would be battling it out everywhere! Being a hero would mean learning to use your power, but where would you go to study? The Hero Academy of course! But what would you do if you were one of the 20 percent who were born Quirkless? Middle school student Izuku Midoriya wants to be a hero more than anything, but he hasn’t got an ounce of power in him. With no chance of ever getting into the prestigious U.A. High School for budding heroes, his life is looking more and more like a dead end. Then an encounter with All Might, the greatest hero of them all, gives him a chance to change his destiny…",
  },
  {
    id: "vol2",
    title: "Volume 2: Rage, You Damned Nerd",
    image: "https://m.media-amazon.com/images/I/81ctOuD4lIL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "3 November 2015",
    category: "Main Series",
    language: "English",
    description:
      "Getting into U.A. High School was difficult enough, but it was only the beginning of Midoriya’s long road toward becoming a superhero. The new students all have amazing powers, and although Midoriya has inherited All Might’s abilities, he can barely control them. What’s more, the first-year students are told they will have to compete just to avoid being expelled!",
  },
  {
    id: "vol3",
    title: "Volume 3: All Might",
    image: "https://m.media-amazon.com/images/I/815IWVldmFL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 February 2016",
    category: "Main Series",
    language: "English",
    description:
      "A sinister group of villains has attacked the first-year U.A. students, but their real target is All Might. It’s all that Midoriya and his classmates can do to hold them off until reinforcements arrive. All Might joins the battle to protect the kids, but as his power runs out, he may be forced into an extremely dangerous bluff!",
  },
  {
    id: "vol4",
    title: "Volume 4: The Boy Born with Everything",
    image: "https://m.media-amazon.com/images/I/91Os+dWdLdL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "3 May 2016",
    category: "Main Series",
    language: "English",
    description:
      "The U.A. High sports festival is a chance for the budding heroes to show their stuff and find a superhero mentor. The students have already struggled through a grueling preliminary round, but now they have to team up to prove they’re capable of moving on to the next stage. The whole country is watching, and so are the shadowy forces that attacked the academy…",
  },
  {
    id: "vol5",
    title: "Volume 5: Todoroki Shoto: Origin",
    image: "https://m.media-amazon.com/images/I/819S87qt98L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 August 2016",
    category: "Main Series",
    language: "English",
    description:
      "The final stages of the U.A. High sports festival promise to be explosive, as Uraraka takes on Bakugo in a head-to-head match! Bakugo never gives anyone a break, and the crowd holds its breath as the battle begins. The finals will push the students of Class 1-A to their limits and beyond!",
  },
  {
    id: "vol6",
    title: "Volume 6: Struggle!",
    image: "https://m.media-amazon.com/images/I/81RF6hFOnvL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 November 2016",
    category: "Main Series",
    language: "English",
    description:
      "In the aftermath of the sports festival, the Class 1-A students begin their internships. Midoriya goes to study under Gran Torino, who was once All Might’s mentor. Gran Torino appears to be a washed-up nutjob, but the old hero still has more moves than a football team, and Midoriya has a lot to learn! Elsewhere, the League of Villains enacts another sinister plot and unleashes a terrifying new enemy!",
  },
  {
    id: "vol7",
    title: "Volume 7: Katsuki Bakugo: Origin",
    image: "https://m.media-amazon.com/images/I/81f274gTf3L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "7 February 2017",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya has learned a few tricks from Gran Torino, but some things just have to be experienced to be understood. Even though he’s not ready, when the League of Villains attacks in the town of Hosu, Midoriya rushes to help Ida, who is engaged in a life-and-death struggle with Hero Killer Stain. Stain has some very particular ideas about heroes and their place in society—and he means to purge the world of every hero he can find!",
  },
  {
    id: "vol8",
    title: "Volume 8: Yaoyorozu Rising",
    image: "https://m.media-amazon.com/images/I/81VCYrUAqiL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 May 2017",
    category: "Main Series",
    language: "English",
    description:
      "The U.A. students have reached the practical portion of their final exam, but they didn’t expect to have to beat their own teachers in order to pass! Paired with his archrival Bakugo, Midoriya has to try to take on none other than All Might himself. Working with Bakugo is one thing, but is giving everything he’s got to beat All Might more than Midoriya can handle? And in a nearby arena, Yaoyorozu and Todoroki endure a similar struggle. Meanwhile, a sinister new adversary prepares to make a move…",
  },
  {
    id: "vol9",
    title: "Volume 9: My Hero",
    image: "https://m.media-amazon.com/images/I/81eVrBK23SL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 August 2017",
    category: "Main Series",
    language: "English",
    description:
      "It’s off to summer camp for Midoriya and the U.A. students! But this is no ordinary vacation—it’s high-impact training where the students are expected to develop their Quirks even further! The teachers have set up some tough challenges, but none will be as difficult and as life changing as the threat a new group of enemies poses. What’s even worse is who the villains’ target is and why…",
  },
  {
    id: "vol10",
    title: "Volume 10: All For One",
    image: "https://m.media-amazon.com/images/I/81BukbxPXDL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "7 November 2017",
    category: "Main Series",
    language: "English",
    description:
      "The League of Villains has kidnapped Bakugo, and the resulting negative publicity has thrown U.A. into a huge uproar. With the public’s trust in heroes threatened, the faculty convenes to figure out what to do. But Midoriya and the students of Class 1-A have plans of their own—an operation to rescue Bakugo that could get them thrown out of school!",
  },
  {
    id: "vol11",
    title: "Volume 11: End of the Beginning, Beginning of the End",
    image: "https://m.media-amazon.com/images/I/81pqu3-+PSL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "6 February 2018",
    category: "Main Series",
    language: "English",
    description:
      "Bakugo’s abduction by the League of Villains was a carefully calculated move designed to draw out the heroes—All Might in particular—and destroy them. Midoriya and his friends set out on a rescue mission that eventually pulls in not only All Might but also several other heroes! The casualties mount, until at last the mastermind of the plot appears—All for One, the only villain powerful enough to take on All Might head-to-head and possibly win!",
  },
  {
    id: "vol12",
    title: "Volume 12: The Test",
    image: "https://m.media-amazon.com/images/I/917qS1EqK9L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "3 April 2018",
    category: "Main Series",
    language: "English",
    description:
      "Class 1-A is working on developing their ultimate moves—a process that will test their strength and creativity in all-new ways! To help them out, Mei Hatsume, a student from the Support Course, is brought in to develop improvements to their costumes. The attention from Mei might be more than Midoriya can handle, but he’ll need every edge he can get to pass the next hurdle for the students of U.A.—the Provisional Licensing Exam!",
  },
  {
    id: "vol13",
    title: "Volume 13: A Talk About Your Quirk",
    image: "https://m.media-amazon.com/images/I/81vzSKLUBDL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 June 2018",
    category: "Main Series",
    language: "English",
    description:
      "The students of Class 1-A have reached another milestone—the Provisional Licensing Exam. After making it through the first part of the test, they ready themselves for the next phase, which takes place in a simulated disaster area. Midoriya and his friends have to rescue as many victims as they can, and although the students of rival Shiketsu High are technically supposed to be helping, competition between them is fierce and even dangerous! As the scenario unfolds and villains arrive to shake things up, the U.A. students will have to find new ways to work with each other and make use of their Quirks.",
  },
  {
    id: "vol14",
    title: "Volume 14: Overhaul",
    image: "https://m.media-amazon.com/images/I/8111p2X1ATL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "7 August 2018",
    category: "Main Series",
    language: "English",
    description:
      "Summer vacation is over, and it’s back to school for the students of U.A. High! But before classes can get started, Midoriya and Bakugo need to settle a beef between them that’s been a long time coming. Even if they can get past this bump in the road on the way to becoming superheroes, the hurdles will just keep getting higher and higher—the hero work studies in the upcoming year will bring them even closer to their goal…or their destruction!",
  },
  {
    id: "vol15",
    title: "Volume 15: Fighting Fate",
    image: "https://m.media-amazon.com/images/I/81qd2KQ-gzL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 October 2018",
    category: "Main Series",
    language: "English",
    description:
      "A new and sinister enemy appears in the form of Chisaki Kai, the young leader of the Hassaikai yakuza gang. Looking to fill the power vacuum left by All For One, Chisaki makes contact with the League of Villains to gain possible support. When a chance run-in with a scared little girl brings Midoriya and his mentor Mirio face-to-face with Chisaki, none of them have any idea how much their lives are about to change.",
  },
  {
    id: "vol16",
    title: "Volume 16: Red Riot",
    image: "https://m.media-amazon.com/images/I/81yHtpGM7YL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 December 2018",
    category: "Main Series",
    language: "English",
    description:
      "The Hassaikai crime gang, led by the young boss Chisaki, has been working on a plan to distribute a Quirk-destroying drug. The key to this evil scheme is the young girl Eri, held prisoner in Chisaki’s hideout. Nighteye asks other heroes to form a team to launch a rescue attempt—and the students of Class 1-A are going into the lion’s den with them! But Nighteye, who can see the future, refuses to look at the fates of anyone on the mission…",
  },
  {
    id: "vol17",
    title: "Volume 17: Lemillion",
    image: "https://m.media-amazon.com/images/I/8163ycaXS3L._SY466_.jpg",
    author: "Kohei Horikoshi",
    date: "9 February 2019",
    category: "Main Series",
    language: "English",
    description:
      "The raid on the Hassaikai gang is in full swing, and the heroes plunge into the darkness toward their ultimate confrontation. Lemillion engages Overhaul in an attempt to rescue Eri, and the battle reaches a new level of intensity. Midoriya is desperate to help his mentor, but what fate has Nighteye foreseen for them all in this clash? And does the key to Midoriya’s survival lie in Eri herself?",
  },
  {
    id: "vol18",
    title: "Volume 18: Bright Future",
    image: "https://m.media-amazon.com/images/I/81hwHys6PLL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 April 2019",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya is in the fight of his life—an all-out battle with Overhaul, who has unleashed his terrifying power. Midoriya is matching it with his own power, pushing One For All to 100 percent. Only by relying on Eri’s restoration Quirk can he hope to take down Overhaul. If Midoriya manages to walk away from this fight, his life will never be the same again…",
  },
  {
    id: "vol19",
    title: "Volume 19: School Festival",
    image: "https://m.media-amazon.com/images/I/81hBurIehoL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 June 2019",
    category: "Main Series",
    language: "English",
    description:
      "In the wake of tragedy, Class 1-A prepares for the upcoming culture festival. While the students are busy planning for success, other forces are at work with their own agendas, and Midoriya, amid the preparations, continues to train with All Might. But when he runs into the failed hero Gentle Criminal, what lesson will he learn?",
  },
  {
    id: "vol20",
    title: "Volume 20: School Festival Start!!",
    image: "https://m.media-amazon.com/images/I/813dlh9e7EL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "6 August 2019",
    category: "Main Series",
    language: "English",
    description:
      "With All Might in retirement, Endeavor takes up the mantle of the number one hero, a position he’s coveted for years. But now that he has it, he’s not entirely comfortable with the responsibilities and risks that come with it—both heroes and villains are always gunning for number one. What does the future hold for Midoriya, and what do his dreams about One For All mean?",
  },
  {
    id: "vol21",
    title: "Volume 21: Why He Gets Back Up",
    image: "https://m.media-amazon.com/images/I/81-BRPwS6-L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 October 2019",
    category: "Main Series",
    language: "English",
    description:
      "Endeavor and Dabi’s battle rages across the city as Endeavor fights to solidify his new position as the number one hero. Hawks provides support, but where do his loyalties really lie? Midoriya experiences a cryptic dream about the past—what secrets do the previous wielders of One For All have to show him? Then Class 1-A’s joint battle training with Class B begins.",
  },
  {
    id: "vol22",
    title: "Volume 22: That Which Is Inherited",
    image: "https://m.media-amazon.com/images/I/91dQnpyYL9L._SY466_.jpg",
    author: "Kohei Horikoshi",
    date: "3 December 2019",
    category: "Main Series",
    language: "English",
    description:
      "In the third match of the joint battle training, the students of Class 1-A have their hands full dealing with the unexpected creativity of Class B’s Quirk use. These matches give everyone a chance to reflect on exactly where they all stand in relation to each other, and on the events in their lives that have brought them to this point. Then it’s time for Bakugo to show what he’s learned…",
  },
  {
    id: "vol23",
    title: "Volume 23: Our Brawl",
    image: "https://m.media-amazon.com/images/I/81LQ6ATTrVL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 February 2020",
    category: "Main Series",
    language: "English",
    description:
      "The final match of the battle training between Class A and Class B continues. Zapped by Shinso’s mind control, Midoriya enters a fugue state where he meets one of the former users of One For All. What powerful Quirks have yet to be unlocked? Midoriya will surely need the full potential of One For All someday, but in the meantime, a new enemy—the Meta Liberation Army—begins to make its moves.",
  },
  {
    id: "vol24",
    title: "Volume 24: All It Takes Is One Bad Day",
    image: "https://m.media-amazon.com/images/I/81Vc4Dt8hzL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "2 June 2020",
    category: "Main Series",
    language: "English",
    description:
      "A new player emerges in the underground world of villains in the form of the Meta Liberation Army. Led by the CEO of the Detnerat Corporation, the MLA is preparing for a new metahuman revolution. In their eyes, the League of Villains is an obstacle to be removed, but Tomura and his band of miscreants aren’t about to go down quietly. It’s army versus league in all-out war, and dominance must be established.",
  },
  {
    id: "vol25",
    title: "Volume 25: Tomura Shigaraki: Origin",
    image: "https://m.media-amazon.com/images/I/81BvXpFXklL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "6 October 2020",
    category: "Main Series",
    language: "English",
    description:
      "Since the terrifying incident when Tomura’s Quirk manifested, only the greatest villain of them all, All For One, has been able to speak to the broken young boy’s heart. The consequences of that fateful meeting play out in the present as Tomura and Re-Destro, the leader of the Meta Liberation Army, battle for supremacy—and if it takes leveling a whole city to sort out who’s on top, so be it!",
  },
  {
    id: "vol26",
    title: "Volume 26: The High Deep Blue Sky",
    image: "https://m.media-amazon.com/images/I/81chNo+roXL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 January 2021",
    category: "Main Series",
    language: "English",
    description:
      "Hawks and the Safety Commission have managed to get their hands on some top secret information. A big villain attack is coming, and the heroes must do all they can to prepare. As part of these preparations, Eraser Head and Present Mic pay a visit to Tartarus prison, while Midoriya, Bakugo and Todoroki begin training under Endeavor in order to become fighters who can stand on their own. In the meantime, the boys will have to survive a dinner party at the Todoroki household!",
  },
  {
    id: "vol27",
    title: "Volume 27: One's Justice",
    image: "https://m.media-amazon.com/images/I/81oGQi3K+5L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "6 April 2021",
    category: "Main Series",
    language: "English",
    description:
      "The confrontation between the heroes and the villains of the Paranormal Liberation Front is about to kick off! With so much at stake, even the students of U.A. have joined the heroes to help in the coming battles. Within the PLF, Hawks continues to play a dangerous game as a double agent, but the villains have fearsome resources of their own, including whatever lurks in the doctor’s lab. Plus, with every moment that passes, Tomura Shigaraki comes closer to his ultimate form… When it all gets started, there won’t be any going back!",
  },
  {
    id: "vol28",
    title: "Volume 28: The Thrill of Destruction",
    image: "https://m.media-amazon.com/images/I/81Ca0MnQELL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 June 2021",
    category: "Main Series",
    language: "English",
    description:
      "The all-out war against the Paranormal Liberation Front continues at the hospital and the mountain villa! Mirko desperately battles High-Ends in order to reach Tomura’s stasis tank, knowing exactly how much is at stake if she fails. At the PLF hideout, Dabi is determined to roast Hawks, but Tokoyami isn’t about to let his mentor fall. Meanwhile, while helping to evacuate the city, Midoriya senses an ominous presence in the hospital… With things going from bad to worse, and the heroes’ forces battered and stretched thin, Midoriya realizes the time has come for him to join the fight, even if it may be his last.",
  },
  {
    id: "vol29",
    title: "Volume 29: Katsuki Bakugo Rising",
    image: "https://m.media-amazon.com/images/I/815ePWe0QNL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "7 September 2021",
    category: "Main Series",
    language: "English",
    description:
      "Tomura Shigaraki has finally awakened, and as he begins to unleash his savage powers, the heroes realize it’s going to take everyone and everything they have to stop him. Several heroes have been lost already, and even as the number one hero, Endeavor, takes on Tomura, Midoriya and Bakugo must put themselves on the line. Meanwhile, the massive villain Gigantomachia rampages toward Jaku City, and it seems nothing can stop him—but the students of U.A. are determined to succeed or die trying…",
  },
  {
    id: "vol30",
    title: "Volume 30: Dabi's Dance",
    image: "https://m.media-amazon.com/images/I/71DY51qxApL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 March 2022",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya and Tomura have finally come to blows and the battle intensifies as Tomura tries to steal One For All. The clash extends into the One For All spirit realm, where the previous users and even All For One join the struggle. While the battle for the ultimate Quirk rages, the other heroes and villains duke it out. Ochaco finds herself taking on Toga, who doesn’t want a fight so much as a heart-to-heart? Then, Dabi finally arrives in Jaku City with a shocking revelation…",
  },
  {
    id: "vol31",
    title: "Volume 31: Izuku Midoriya and Toshinori Yagi",
    image: "https://m.media-amazon.com/images/I/71QxQ+x1alL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 July 2022",
    category: "Main Series",
    language: "English",
    description:
      "In the aftermath of the battle in Jaku City, the forces of good are reeling. With so many heroes dead, it seems like society itself is on the verge of collapse. Although Midoriya and the others have managed to drive off Tomura, All For One is only just getting started. As the dust settles, the Todoroki family must finally face their troubled past, and Midoriya begins to understand what One For All really is and that reaching his full potential might test his convictions…",
  },
  {
    id: "vol32",
    title: "Volume 32: Your Turn",
    image: "https://m.media-amazon.com/images/I/81w8zife3TL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 October 2022",
    category: "Main Series",
    language: "English",
    description:
      "With society wavering on the verge of collapse in the wake of the recent chaos, Midoriya has left his school and friends behind in order to save whatever lives he can out on the streets and lure All For One into the open. But the mastermind villain has his own plans and sends villains for hire after Midoriya, including one familiar face. Chief among these hired guns is Lady Nagant—a fallen former hero who delivers plenty of bang for her buck.",
  },
  {
    id: "vol33",
    title: "Volume 33: From Class A to One For All",
    image: "https://m.media-amazon.com/images/I/81d6Cqu7GoL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "7 February 2023",
    category: "Main Series",
    language: "English",
    description:
      "Knowing that All For One has put a target on his back, Midoriya has left U.A., hoping to draw the villains away from everyone he cares about. But his friends know the newest bearer of One For All shouldn’t handle this burden alone, so they set out to bring him back. The forces of good need every hero they can find as the unfolding crisis in Japan now has global ramifications, with even foreign heroes itching to join the fight…",
  },
  {
    id: "vol34",
    title: "Volume 34: United States of America",
    image: "https://m.media-amazon.com/images/I/811WD+Wwf9L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "8 June 2023",
    category: "Main Series",
    language: "English",
    description:
      "All For One’s will has taken root in Tomura’s mind, and this new entity is now a global threat. Even so, the United Nations is hesitant to dispatch heroes to Japan, but Star and Stripe—the U.S.A.’s number one hero—arrives to tackle this menace head-on. In the skies over the Pacific, the combatants size each other up, trying to gain an advantage, but there’s no telling who’ll be left standing after the dust settles on this epic duel…",
  },
  {
    id: "vol35",
    title: "Volume 35: Battle Flame",
    image: "https://m.media-amazon.com/images/I/81PrVZSWhaL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 September 2023",
    category: "Main Series",
    language: "English",
    description:
      "The ultimate war between heroes and villains looms in the near future as both sides regroup. Japan’s heroes weave their plans in the lead-up, but will spies within U.A. give it all away? The Hero Course students will have their parts to play as well, and Midoriya himself will have a major role. If things work out, the heroes hope to divide and conquer, but even the best-laid plans rarely survive contact with the enemy…",
  },
  {
    id: "vol36",
    title: "Volume 36: Two Flashfired",
    image: "https://m.media-amazon.com/images/I/81mydGNiOAL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 December 2023",
    category: "Main Series",
    language: "English",
    description:
      "The plan to engage the villains on the heroes’ terms has mostly succeeded. Now in different locations around Japan, the heroes and U.A. students take on the villains in all-out battles! First, Todoroki squares off against Dabi with terrifying intensity. Elsewhere, Endeavor and Hawks hope to turn the tables on All For One, but the villain mastermind has one last trick up his sleeve. Finally, it’s Tomura’s new and improved body versus the crew at the airborne U.A., where the youngest heroes have critical roles to play!",
  },
  {
    id: "vol37",
    title: "Volume 37: Those Who Defend, Those Who Violate",
    image: "https://m.media-amazon.com/images/I/81SOYxpzU3L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "5 March 2024",
    category: "Main Series",
    language: "English",
    description:
      "The terrifying fusion of Tomura and All For One now seems unstoppable. Since the villains have the upper hand, even the president of the United States is considering the unthinkable—capitulating to Tomura. But Mirko, Edgeshot, and Jeanist are still on the scene, holding on for dear life. The heroes’ big plan was always to pit Midoriya against Tomura, and when the young hero finally arrives and sees what’s happened, all bets are off—Midoriya’s ready to face his deadly rival!",
  },
  {
    id: "vol38",
    title: "Volume 38: Hopes",
    image: "https://m.media-amazon.com/images/I/81G4Gy7S4xL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "4 June 2024",
    category: "Main Series",
    language: "English",
    description:
      "In the desperate battle with All For One and his minions, the U.A. students are pushing themselves to their absolute limits. Everywhere, the villains have the upper hand. As the floating U.A. island falls out of the sky, Ochaco and Asui fight Himiko Toga, and Midoriya squares off with Tomura. All For One’s new form appears all but unstoppable, and if he reaches Tomura, all is lost. But one hero stands in his way…",
  },
  {
    id: "vol39",
    title: "Volume 39: Battle Without A Quirk",
    image: "https://m.media-amazon.com/images/I/81HdBTnVtHL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "1 October 2024",
    category: "Main Series",
    language: "English",
    description:
      "Endeavor and Dabi clash as the villain reaches critical mass, but Endeavor’s path to victory may also lead to his own destruction. Elsewhere, Ochaco tries to talk Himiko Toga down. She’ll have to find something inside Toga to appeal to before it’s too late. Both of these battles circle the main event—All Might versus All For One—in a showdown that’s been a long time coming. But All Might is a shadow of his former self—can he still go the distance?",
  },
  {
    id: "vol40",
    title: "Volume 40: The End of an Era, and...",
    image: "https://m.media-amazon.com/images/I/810xbKIOp5L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "11 February 2025",
    category: "Main Series",
    language: "English",
    description:
      "Only one man is walking away from the epic rematch between All Might and All For One. All Might’s superpowers may be long gone, but he’s no less of a superhero as he throws everything he’s got at the diabolical mastermind. Meanwhile, All For One wants nothing more than to reach Tomura—his ideal vessel. With the whole world watching and All Might hanging on by his fingernails, one young protégé of his might have to step up to save the day.",
  },
  {
    id: "vol41",
    title: "Volume 41: Overlay",
    image: "https://m.media-amazon.com/images/I/81vg9LPebQL._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "3 June 2025",
    category: "Main Series",
    language: "English",
    description:
      "Midoriya’s epic final battle with Shigaraki reaches its earth-shattering crescendo! With Danger Sense stolen away and the villain threatening to wipe Japan off the map, Midoriya has to get really creative with his Quirks to survive. The Second’s plan to smash the vestiges of One For All into the core of Shigaraki’s psychic space is the last chance the heroes have to stop All For One’s grand schemes from coming to fruition. But first, Midoriya has to land a solid punch",
  },
  {
    id: "vol42",
    title: "Volume 42: I Am Here!",
    image: "https://m.media-amazon.com/images/I/81XBuM1B0-L._SL1500_.jpg",
    author: "Kohei Horikoshi",
    date: "21 October 2025",
    category: "Main Series",
    language: "English",
    description:
      "For a time, the fate of the world was balanced on a knife’s edge between salvation and doom, held in the palm of Izuku Midoriya’s hand. Everything was riding on the outcome of the Quirk-based war to end all wars. What became of the students and staff of U.A. High? How did they rebuild their lives after the epic conflict? Did superpowered society come away with the lessons it needed to learn? Find out in the final volume of My Hero Academia!",
  },
  {
    id: "vol42_bn",
    title: "Volume 42 (Variant Cover)",
    image:
      "https://prodimage.images-bn.com/pimages/9781974762194_p1_v2_s1200x1200.jpg",
    author: "Kohei Horikoshi",
    date: "21 October 2025",
    category: "Main Series",
    language: "English",
    description:
      "For a time, the fate of the world was balanced on a knife’s edge between salvation and doom, held in the palm of Izuku Midoriya’s hand. Everything was riding on the outcome of the Quirk-based war to end all wars. What became of the students and staff of U.A. High? How did they rebuild their lives after the epic conflict? Did superpowered society come away with the lessons it needed to learn? Find out in the final volume of My Hero Academia!",
  },
  {
    id: "vol42_bam",
    title: "Volume 42 (Variant Cover)",
    image: "https://i.ibb.co/kjc7pwH/1974762203.png",
    author: "Kohei Horikoshi",
    date: "21 October 2025",
    category: "Main Series",
    language: "English",
    description:
      "For a time, the fate of the world was balanced on a knife’s edge between salvation and doom, held in the palm of Izuku Midoriya’s hand. Everything was riding on the outcome of the Quirk-based war to end all wars. What became of the students and staff of U.A. High? How did they rebuild their lives after the epic conflict? Did superpowered society come away with the lessons it needed to learn? Find out in the final volume of My Hero Academia!",
  },
  {
    id: "vol42_wal",
    title: "Volume 42 (Variant Cover)",
    image: "https://i.ibb.co/Psb7DxpN/Screenshot-2025-11-24-at-12-12-18-AM.png",
    author: "Kohei Horikoshi",
    date: "21 October 2025",
    category: "Main Series",
    language: "English",
    description:
      "For a time, the fate of the world was balanced on a knife’s edge between salvation and doom, held in the palm of Izuku Midoriya’s hand. Everything was riding on the outcome of the Quirk-based war to end all wars. What became of the students and staff of U.A. High? How did they rebuild their lives after the epic conflict? Did superpowered society come away with the lessons it needed to learn? Find out in the final volume of My Hero Academia!",
  },
  {
    id: "vol0",
    title: "Volume Origin",
    image: "https://i.ibb.co/B5gQC4r1/Volume-Origin.png",
    author: "Kohei Horikoshi",
    date: "3 August 2018",
    category: "Movie Tie-In",
    language: "Japanese",
    description:
      "This book includes information from the movie! So please be careful and read it at your own risk.",
  },
  {
    id: "volr",
    title: "Volume Rising",
    image: "https://i.ibb.co/q4dczmT/Volume-Rising.png",
    author: "Kohei Horikoshi",
    date: "20 December 2019",
    category: "Movie Tie-In",
    language: "Japanese",
    description:
      "The second movie! Thank you for coming! The animation production team has made another awesome movie! Please come and see Class 1-A going Plus Ultra!",
  },
  {
    id: "volw",
    title: "Volume World Heroes",
    image: "https://i.ibb.co/2Q4v3kb/Volume-World-Heroes.png",
    author: "Kohei Horikoshi",
    date: "6 August 2021",
    category: "Movie Tie-In",
    language: "English",
    description:
      "The third movie! Thank you for your interest! Isn't it great to have three movies made? Thank you! Thank you world!",
  },
  {
    id: "voln",
    title: "Volume Next",
    image: "https://i.ibb.co/KzS4Hm0B/Volume-Next.png",
    author: "Kohei Horikoshi",
    date: "2 August 2024",
    category: "Movie Tie-In",
    language: "Japan",
    description:
      "The fourth film! I'm so thankful to everyone who watched it! People sometimes tell me that working hard is a given, but even though it's normal, I still believe it's cool! I'd like to think someone doing their best is super cool!",
  },
];
